Add unit tests for org.keycloak.models.utils.Base32Test
Diffblue-benchmarks/keycloak pull request #2
Opened 2019-07-26 16:36 UTC by ThomasPerkins1123

Hi,

I've analysed your code base and noticed that `org.keycloak.models.utils.Base32Test` in the `keycloak-server-spi` module is not fully tested.

I've written some tests that cover this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests should help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other particular classes that you consider important.

2019-07-30 09:56 UTC, paulkennethkent requested changes

2019-07-30 09:56 UTC, paulkennethkent commented on server-spi/src/test/java/org/keycloak/models/utils/Base32Test.java
> +}
Add a newline

2019-07-30 15:47 UTC, petersear reviewed
I'd suggest either combining all of the tests for each method into one test method or giving them more interesting names.
Also, you could switch the order around, so that encode() is tested before decode(), to match the order of the methods in the class under test.

2019-07-31 09:04 UTC, paulkennethkent commented
I agree with Peter unless there is a reason you separated them out this time?

2019-07-31 09:36 UTC, petersear requested changes

2019-07-31 09:36 UTC, petersear commented on server-spi/src/test/java/org/keycloak/models/utils/Base32Test.java
> +	@Test
Add blank line before `@Test`

2019-07-31 09:36 UTC, petersear commented on server-spi/src/test/java/org/keycloak/models/utils/Base32Test.java
> +
Delete blank line at line 27.

2019-08-01 09:04 UTC, petersear approved these changes

2019-08-01 09:09 UTC, JohnLBergqvist approved these changes

2019-08-06 07:45 UTC, paulkennethkent approved these changes

2019-09-04 08:54 UTC, closed without merging